<?php
    session_start();
    require_once("dao.php");
    //require_once("KLogger.php");
    //$logger = new KLogger ("log.txt" , KLogger::WARN); //TODO: ADD LOGGER

    $username = $_POST['username'];
    $password = $_POST['password'];
    $password_repeat = $_POST['password_repeat'];

    //$logger->LogDebug("User [{$username}] attempting to sign up");

    $dao = new Dao();
    $user = $dao->getUserFromName("'" . $username . "'");

    // Check if passwords match
    if ($password != $password_repeat) {
        $status = "Passwords must both match";
        $_SESSION["status"] = $status;
        $_SESSION["logged_in"] = false;
        header("Location: ./signup.php");
        exit();
    }

    // Check if password is of the correct length
    if (strlen($password) < 3) { //TODO: make longer, shot for testing purposes
        $status = "Passwords must be at least 3 characters";
        $_SESSION["status"] = $status;
        $_SESSION["logged_in"] = false;
        header("Location: ./signup.php");
        exit();
    }

    // Check if username is of right length
    if (strlen($username) > 16) {
        $status = "Username must be 16 characters or less";
        $_SESSION["status"] = $status;
        $_SESSION["logged_in"] = false;
        header("Location: ./signup.php");
        exit();
    }

    // Check if username already exists
    if (sizeof($user) != 0) {
        $status = "Username already taken";
        $_SESSION["status"] = $status;
        $_SESSION["logged_in"] = false;
        header("Location: ./signup.php");
        exit();
    }

    // Check if username contains "guest" so as not to take an autogenerated name
    if (str_contains($username, "guest")) {
        $status = "Username cannot contain 'guest' (reserved keyword)";
        $_SESSION["status"] = $status;
        $_SESSION["logged_in"] = false;
        header("Location: ./signup.php");
        exit();
    }
    
    $dao->createUser($username, $password);
    $user = $dao->getUserFromName("'" . $username . "'");
    $_SESSION["logged_in"] = true;
    $_SESSION["user_id"] = $user[0]["user_id"];
    header("Location: ./desktop.php");
    exit();